name: C/C++ CI

on:
  push:
    branches: [ "nsf-midi" ]
  pull_request:
    branches: [ "nsf-midi" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: |
        apt-get update && apt-get -y install build-essential mingw-w64 mkdocs
        make -C icarus platform=windows compiler="x86_64-w64-mingw32-g++" windres="x86_64-w64-mingw32-windres"
        make -C higan target=higan platform=windows compiler="x86_64-w64-mingw32-g++" windres="x86_64-w64-mingw32-windres"
        LC_ALL=C.UTF-8 mkdocs build
        mkdir higan-nightly
        cp -a icarus/out/icarus higan-nightly/icarus.exe
        cp -a icarus/Database higan-nightly/
        cp -a icarus/Firmware higan-nightly/
        cp -a higan/out/higan higan-nightly/higan.exe
        cp -a higan/systems/ higan-nightly/
        cp -a shaders higan-nightly/
        cp -a docs_build higan-nightly/docs
        cp -a GPLv3.txt higan-nightly/

